-- CREATE TABLET

CREATE TABLE CANAL(
CanalID int Primary Key,
Nome varchar(150) NOT NULL,
ContagemInscritos int DEFAULT 0,
DataCriacao datetime NOT NULL);

CREATE TABLE VIDEO(
VideoID int Primary Key,
Nome varchar(150) NOT NULL,
Vizualizacoes int DEFAULT 0,
Likes int DEFAULT 0,
Deslikes int DEFAULT 0,
Duracao int DEFAULT 0,
CanalID int Foreign Key REFERENCES CANAL(CanalID));

-- INSERT INTO

INSERT INTO CANAL(CanalID, Nome, ContagemInscritos, DataCriacao)
VALUES(4, 'Aula SQL', 25, 2023-01-01)

INSERT INTO VIDEO(VideoID, Nome, Vizualizacoes, Likes, Deslikes)
VALUES(1, 'Aula SQL', 25, 2023-01-01)
select * from CANAL

-- Copiar tabela

SELECT * INTO CANAL_NOVO FROM CANAL

SELECT * FROM CANAL_NOVO

-- FUNÇÃO UPDATE: ALTERAR LINHAS DO CODIGO
UPDATE CANAL
SET Nome = 'AULA NOVA'
WHERE CanalID =2

SELECT * FROM CANAL

-- FUNÇÃO DELETE: APAGAR LINHAS

DELETE FROM CANAL
WHERE CanalID =4
SELECT * FROM CANAL

-- FUNÇÃO ALTER TABLE: ALTERET A ESTRUTURA DE UMA TABELA, ADD REM COLUNAS, SETAR VALORES PADRAO PARA COLUNA
-- ADD OU REMOVE RESTRICOES, RENOMEAR TABELA

-- ADD COLUNA
ALTER TABLE CANAL
ADD ativo bit

SELECT * FROM CANAL

-- ALTERANDO O TIPO DA COLUNA
ALTER TABLE CANAL
ALTER COLUMN Nome varchar (200) NOT NULL

-- FUNÇÃO DROP TABLE: EXCLUIR UMA TABELA
 
 DROP TABLE CANAL_NOVO

 -- DELETAR APENAS O CONTEUDO DA TABELA

 TRUNCATE TABLE CANAL_NOVO

 -- CHECK CONSTRAINT: CRIAR RESTRIÇÕES SOBRE VALORES
 -- NOT NULL CONSTRAINT: FORÇA COM O QUE O VALOR SEJA PREENCHIDO	
 
 -- UNIQUE CONSTRINT: SÓ PERMITE VALORES UNICOS NA COLUNA
 CREATE TABLE inscritos (
 Id int NOT NULL UNIQUE,
 Nome varchar(150) NOT NULL,
 Idade int check (Idade >=12)
 );

 INSERT INTO inscritos(Id, Nome, Idade) values (1, 'Rafael', 12)
 SELECT * FROM inscritos

 -- VIEWS: TABELAS CRIADAS PARA CONSULTAS
 CREATE VIEW [TESTE] AS
 SELECT * FROM CANAL
 WHERE CanalID = 2

 SELECT * FROM [TESTE]

